[package]
name = "llcap-server"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
clap = { version = "4.5.37", features = ["derive"] }
libc = "0.2.172"
num-traits = "0.2.19"

[build-dependencies]
bindgen = "0.71.1"