VSTR_VAL_SPAIR(int, 0)
VSTR_VAL_SPAIR(float, 1)
VSTR_VAL_SPAIR(double, 2)
VSTR_VAL_SPAIR(char, 3)
VSTR_VAL_SPAIR(unsigned, 4)
VSTR_VAL_SPAIR(unsigned char, 5)
VSTR_VAL_SPAIR(long, 6)
VSTR_VAL_SPAIR(long long, 7)
VSTR_VAL_SPAIR(short, 8)
VSTR_VAL_SPAIR(long double, 9)
VSTR_VAL_SPAIR(unsigned long, 10)
VSTR_VAL_SPAIR(unsigned short, 11)
VSTR_VAL_SPAIR(signed char, 12)
VSTR_VAL_SPAIR(wchar_t, 13)
VSTR_VAL_SPAIR(char16_t, 15)
VSTR_VAL_SPAIR(char32_t, 16)
VSTR_VAL_SPAIR(bool, 18)