FROM fedora:42 as BUILD

# dependencies for LLVM
RUN dnf install -y git make cmake ninja xargs clang clang++ @development-tools

# research project repo location
WORKDIR /opt/llcap

# to allow invalidation of cache
ARG BUILDCLONE=cached
RUN git clone "https://gitlab.mff.cuni.cz/vasutro/research-project.git"
WORKDIR /opt/llcap/research-project
RUN git submodule update --init --depth=1 ./sandbox/llvm-project

# apply our LLVM patch
WORKDIR /opt/llcap/research-project/sandbox/llvm-project
RUN git apply ../01-llvm-ir/clang-ir-mapping-llvm.diff

# build
WORKDIR /opt/llcap/research-project/sandbox
RUN ./setup-llvm-build.sh
WORKDIR /opt/llcap/research-project/sandbox/build
RUN ninja -j $(nproc)

RUN ninja install

# to allow cachec invalidation for non-llvm changes (use on your own risk)
ARG NONLLVMUPDATE=cached
WORKDIR /opt/llcap/research-project
RUN git pull

# AST plugin
WORKDIR /opt/llcap/research-project/sandbox/01-llvm-ir/custom-metadata-pass
RUN ./setup-tool.sh

WORKDIR /opt/llcap/research-project/sandbox/build
RUN ninja -j $(nproc)

RUN ninja install
RUN mkdir -p /opt/manifest/ && cp install_manifest.txt /opt/manifest/install_manifest.txt
RUN ninja clean
WORKDIR /opt/llcap/research-project/sandbox
RUN rm -rf ./llvm-project/*

# IR plugin
WORKDIR /opt/llcap/research-project/sandbox/01-llvm-ir/llvm-pass
RUN cmake ./
RUN make -j $(nproc)

# Hook library
WORKDIR /opt/llcap/research-project/sandbox/02-ipc/ipc-hooklib
RUN cmake ./
RUN make -j $(nproc)

RUN dnf install -y cargo
WORKDIR /opt/llcap/research-project/sandbox/02-ipc/llcap-server
RUN cargo b
RUN cargo b --release
RUN cargo install --root ./ --path ./
RUN cargo clean
# Remove redundancies
RUN rm -rf /opt/llcap/research-project/.git/
# (tested with the example-arg-replacement demo)
RUN find /usr/local/bin/* -not -name 'clang' -not -name 'clang++' -not -name 'clang-21' -delete


FROM fedora:42
# installing from install_manifest.txt (https://github.com/docker/for-linux/issues/1060) also yields multi-GB image, therefore copying it all
COPY --from=BUILD /usr/local/ /usr/local/

WORKDIR /opt/llcap/research-project
# clang, etc for C & C++ standard library
RUN dnf install -y make cmake clang clang++ && dnf clean all -y
COPY --from=BUILD /opt/llcap/* /opt/llcap/research-project

WORKDIR /opt/llcap/research-project/sandbox/02-ipc/example-arg-replacement
CMD bash